app.views = (function() {

    // http://www.accessify.com/tools-and-wizards/developer-tools/html-javascript-convertor/

    var skinSettingsDialog = (function() {
        
var txt="";
txt += "<div id=\"skinSettingsDialog\" title=\"Skin Settings\">";
txt += "            <form id=\"skin-settings\">";
txt += "                <div id=\"web-notify-settings\">";
txt += "                    <h1>Web Notification Settings<\/h1>";
txt += "                    <p>These are small pop-ups that appear on your desktop to show you a chat or PM has been received.<\/p>";
txt += "                    <label><input type=\"checkbox\" id=\"web-notify-chat\" value=\"web-notify-chat\">Notify on chats<\/label>";
txt += "                    <label><input type=\"checkbox\" id=\"web-notify-pm\" value=\"web-notify-pm\">Notify on PMs<\/label>";
txt += "                <\/div>";
txt += "                <div id=\"sound-settings\">                    ";
txt += "                    <h1>Sound Settings<\/h1>";
txt += "                    <div class=\"form-ctrl\">";
txt += "                        <label for=\"SOUND-KAI_CLIENT_CHAT\">New chat message<\/label>";
txt += "                        <select id=\"SOUND-KAI_CLIENT_CHAT\">";
txt += "                            <option>none<\/option>";
txt += "                            <option>chat_1<\/option>";
txt += "                            <option value=\"chat_2\">chat_2 (default)<\/option>";
txt += "                            <option>chat_3<\/option>";
txt += "                            <option>contact_offline<\/option>";
txt += "                            <option>contact_online<\/option>";
txt += "                            <option>detatch_1<\/option>";
txt += "                            <option>detatch_2<\/option>";
txt += "                            <option>detatch_3<\/option>";
txt += "                            <option>detatch_4<\/option>";
txt += "                            <option>enter_1<\/option>";
txt += "                            <option>enter_2<\/option>";
txt += "                            <option>invite_1<\/option>";
txt += "                            <option>invite_2<\/option>";
txt += "                            <option>leave_1<\/option>";
txt += "                            <option>leave_2<\/option>";
txt += "                            <option>pd_ring1<\/option>";
txt += "                            <option>pm_1<\/option>";
txt += "                            <option>pm_2<\/option>";
txt += "                        <\/select>";
txt += "                        <input name=\"PLAY-KAI_CLIENT_CHAT\" class=\"play-btn\" alt=\"play\" type=\"image\" src=\"\/skin\/img\/play_20x20.png\">";
txt += "                    <\/div>";
txt += "                    <div class=\"form-ctrl\">";
txt += "                        <label for=\"SOUND-KAI_CLIENT_JOINS_VECTOR\">Player Joins Room<\/label>";
txt += "                        <select id=\"SOUND-KAI_CLIENT_JOINS_VECTOR\">";
txt += "                            <option>none<\/option>";
txt += "                            <option>chat_1<\/option>";
txt += "                            <option>chat_2<\/option>";
txt += "                            <option>chat_3<\/option>";
txt += "                            <option>contact_offline<\/option>";
txt += "                            <option>contact_online<\/option>";
txt += "                            <option>detatch_1<\/option>";
txt += "                            <option>detatch_2<\/option>";
txt += "                            <option>detatch_3<\/option>";
txt += "                            <option>detatch_4<\/option>";
txt += "                            <option value=\"enter_1\">enter_1 (default)<\/option>";
txt += "                            <option>enter_2<\/option>";
txt += "                            <option>invite_1<\/option>";
txt += "                            <option>invite_2<\/option>";
txt += "                            <option>leave_1<\/option>";
txt += "                            <option>leave_2<\/option>";
txt += "                            <option>pd_ring1<\/option>";
txt += "                            <option>pm_1<\/option>";
txt += "                            <option>pm_2<\/option>";
txt += "                        <\/select>";
txt += "                        <input name=\"PLAY-KAI_CLIENT_JOINS_VECTOR\" class=\"play-btn\" alt=\"play\" type=\"image\" src=\"\/skin\/img\/play_20x20.png\">";
txt += "                    <\/div>";
txt += "                    <div class=\"form-ctrl\">";
txt += "                        <label for=\"SOUND-KAI_CLIENT_LEAVES_VECTOR\">Player Leaves Room<\/label>";
txt += "                        <select id=\"SOUND-KAI_CLIENT_LEAVES_VECTOR\">";
txt += "                            <option>none<\/option>";
txt += "                            <option>chat_1<\/option>";
txt += "                            <option>chat_2<\/option>";
txt += "                            <option>chat_3<\/option>";
txt += "                            <option>contact_offline<\/option>";
txt += "                            <option>contact_online<\/option>";
txt += "                            <option>detatch_1<\/option>";
txt += "                            <option>detatch_2<\/option>";
txt += "                            <option>detatch_3<\/option>";
txt += "                            <option>detatch_4<\/option>";
txt += "                            <option>enter_1<\/option>";
txt += "                            <option>enter_2<\/option>";
txt += "                            <option>invite_1<\/option>";
txt += "                            <option>invite_2<\/option>";
txt += "                            <option value=\"leave_1\">leave_1 (default)<\/option>";
txt += "                            <option>leave_2<\/option>";
txt += "                            <option>pd_ring1<\/option>";
txt += "                            <option>pm_1<\/option>";
txt += "                            <option>pm_2<\/option>";
txt += "                        <\/select>";
txt += "                        <input name=\"PLAY-KAI_CLIENT_LEAVES_VECTOR\" class=\"play-btn\" alt=\"play\" type=\"image\" src=\"\/skin\/img\/play_20x20.png\">";
txt += "                    <\/div>";
txt += "                    <div class=\"form-ctrl\">";
txt += "                        <label for=\"SOUND-KAI_CLIENT_PM\">PM Received<\/label>";
txt += "                        <select id=\"SOUND-KAI_CLIENT_PM\">";
txt += "                            <option>none<\/option>";
txt += "                            <option>chat_1<\/option>";
txt += "                            <option>chat_2<\/option>";
txt += "                            <option>chat_3<\/option>";
txt += "                            <option>contact_offline<\/option>";
txt += "                            <option>contact_online<\/option>";
txt += "                            <option>detatch_1<\/option>";
txt += "                            <option>detatch_2<\/option>";
txt += "                            <option>detatch_3<\/option>";
txt += "                            <option>detatch_4<\/option>";
txt += "                            <option>enter_1<\/option>";
txt += "                            <option>enter_2<\/option>";
txt += "                            <option>invite_1<\/option>";
txt += "                            <option>invite_2<\/option>";
txt += "                            <option>leave_1<\/option>";
txt += "                            <option>leave_2<\/option>";
txt += "                            <option>pd_ring1<\/option>";
txt += "                            <option>pm_1<\/option>";
txt += "                            <option value=\"pm_2\">pm_2 (default)<\/option>";
txt += "                        <\/select>";
txt += "                        <input name=\"PLAY-KAI_CLIENT_PM\" class=\"play-btn\" alt=\"play\" type=\"image\" src=\"\/skin\/img\/play_20x20.png\">";
txt += "                    <\/div>";
txt += "                    <div class=\"form-ctrl\">";
txt += "                        <label for=\"SOUND-KAI_CLIENT_ARENA_PM\">Arena PM Received<\/label>";
txt += "                        <select id=\"SOUND-KAI_CLIENT_ARENA_PM\">";
txt += "                            <option>none<\/option>";
txt += "                            <option>chat_1<\/option>";
txt += "                            <option>chat_2<\/option>";
txt += "                            <option>chat_3<\/option>";
txt += "                            <option>contact_offline<\/option>";
txt += "                            <option>contact_online<\/option>";
txt += "                            <option>detatch_1<\/option>";
txt += "                            <option>detatch_2<\/option>";
txt += "                            <option>detatch_3<\/option>";
txt += "                            <option>detatch_4<\/option>";
txt += "                            <option>enter_1<\/option>";
txt += "                            <option>enter_2<\/option>";
txt += "                            <option>invite_1<\/option>";
txt += "                            <option>invite_2<\/option>";
txt += "                            <option>leave_1<\/option>";
txt += "                            <option>leave_2<\/option>";
txt += "                            <option>pd_ring1<\/option>";
txt += "                            <option value=\"pm_1\">pm_1 (default)<\/option>";
txt += "                            <option>pm_2<\/option>";
txt += "                        <\/select>";
txt += "                        <input name=\"PLAY-KAI_CLIENT_ARENA_PM\" class=\"play-btn\" alt=\"play\" type=\"image\" src=\"\/skin\/img\/play_20x20.png\">";
txt += "                    <\/div>";
txt += "                    <div class=\"form-ctrl\">";
txt += "                        <label for=\"SOUND-KAI_CLIENT_CONTACT_ONLINE\">Contact comes online<\/label>";
txt += "                        <select id=\"SOUND-KAI_CLIENT_CONTACT_ONLINE\">";
txt += "                            <option>none<\/option>";
txt += "                            <option>chat_1<\/option>";
txt += "                            <option>chat_2<\/option>";
txt += "                            <option>chat_3<\/option>";
txt += "                            <option>contact_offline<\/option>";
txt += "                            <option value=\"contact_online\">contact_online (default)<\/option>";
txt += "                            <option>detatch_1<\/option>";
txt += "                            <option>detatch_2<\/option>";
txt += "                            <option>detatch_3<\/option>";
txt += "                            <option>detatch_4<\/option>";
txt += "                            <option>enter_1<\/option>";
txt += "                            <option>enter_2<\/option>";
txt += "                            <option>invite_1<\/option>";
txt += "                            <option>invite_2<\/option>";
txt += "                            <option>leave_1<\/option>";
txt += "                            <option>leave_2<\/option>";
txt += "                            <option>pd_ring1<\/option>";
txt += "                            <option>pm_1<\/option>";
txt += "                            <option>pm_2<\/option>";
txt += "                        <\/select>";
txt += "                        <input name=\"PLAY-KAI_CLIENT_CONTACT_ONLINE\" class=\"play-btn\" alt=\"play\" type=\"image\" src=\"\/skin\/img\/play_20x20.png\">";
txt += "                    <\/div>";
txt += "                    <div class=\"form-ctrl\">";
txt += "                        <label for=\"SOUND-KAI_CLIENT_CONTACT_OFFLINE\">Contact goes offline<\/label>";
txt += "                        <select id=\"SOUND-KAI_CLIENT_CONTACT_OFFLINE\">";
txt += "                            <option>none<\/option>";
txt += "                            <option>chat_1<\/option>";
txt += "                            <option>chat_2<\/option>";
txt += "                            <option>chat_3<\/option>";
txt += "                            <option value=\"contact_offline\">contact_offline (default)<\/option>";
txt += "                            <option>contact_online<\/option>";
txt += "                            <option>detatch_1<\/option>";
txt += "                            <option>detatch_2<\/option>";
txt += "                            <option>detatch_3<\/option>";
txt += "                            <option>detatch_4<\/option>";
txt += "                            <option>enter_1<\/option>";
txt += "                            <option>enter_2<\/option>";
txt += "                            <option>invite_1<\/option>";
txt += "                            <option>invite_2<\/option>";
txt += "                            <option>leave_1<\/option>";
txt += "                            <option>leave_2<\/option>";
txt += "                            <option>pd_ring1<\/option>";
txt += "                            <option>pm_1<\/option>";
txt += "                            <option>pm_2<\/option>";
txt += "                        <\/select>";
txt += "                        <input name=\"PLAY-KAI_CLIENT_CONTACT_OFFLINE\" class=\"play-btn\" alt=\"play\" type=\"image\" src=\"\/skin\/img\/play_20x20.png\">";
txt += "                    <\/div>";
txt += "                    <div class=\"form-ctrl\">";
txt += "                        <label for=\"SOUND-KAI_CLIENT_DETACH\">Detached from XLink Kai Engine<\/label>";
txt += "                        <select id=\"SOUND-KAI_CLIENT_DETACH\">";
txt += "                            <option>none<\/option>";
txt += "                            <option>chat_1<\/option>";
txt += "                            <option>chat_2<\/option>";
txt += "                            <option>chat_3<\/option>";
txt += "                            <option>contact_offline<\/option>";
txt += "                            <option>contact_online<\/option>";
txt += "                            <option value=\"detatch_1\">detatch_1 (default)<\/option>";
txt += "                            <option>detatch_2<\/option>";
txt += "                            <option>detatch_3<\/option>";
txt += "                            <option>detatch_4<\/option>";
txt += "                            <option>enter_1<\/option>";
txt += "                            <option>enter_2<\/option>";
txt += "                            <option>invite_1<\/option>";
txt += "                            <option>invite_2<\/option>";
txt += "                            <option>leave_1<\/option>";
txt += "                            <option>leave_2<\/option>";
txt += "                            <option>pd_ring1<\/option>";
txt += "                            <option>pm_1<\/option>";
txt += "                            <option>pm_2<\/option>";
txt += "                        <\/select>";
txt += "                        <input name=\"PLAY-KAI_CLIENT_DETACH\" class=\"play-btn\" alt=\"play\" type=\"image\" src=\"\/skin\/img\/play_20x20.png\">";
txt += "                    <\/div>";
txt += "                    <div class=\"form-ctrl\">";
txt += "                        <label for=\"SOUND-KAI_CLIENT_INVITE\">Invite received<\/label>";
txt += "                        <select id=\"SOUND-KAI_CLIENT_INVITE\">";
txt += "                            <option>none<\/option>";
txt += "                            <option>chat_1<\/option>";
txt += "                            <option>chat_2<\/option>";
txt += "                            <option>chat_3<\/option>";
txt += "                            <option>contact_offline<\/option>";
txt += "                            <option>contact_online<\/option>";
txt += "                            <option>detatch_1<\/option>";
txt += "                            <option>detatch_2<\/option>";
txt += "                            <option>detatch_3<\/option>";
txt += "                            <option>detatch_4<\/option>";
txt += "                            <option>enter_1<\/option>";
txt += "                            <option>enter_2<\/option>";
txt += "                            <option>invite_1<\/option>";
txt += "                            <option value=\"invite_2\">invite_2 (default)<\/option>";
txt += "                            <option>leave_1<\/option>";
txt += "                            <option>leave_2<\/option>";
txt += "                            <option>pd_ring1<\/option>";
txt += "                            <option>pm_1<\/option>";
txt += "                            <option>pm_2<\/option>";
txt += "                        <\/select>";
txt += "                        <input name=\"PLAY-KAI_CLIENT_INVITE\" class=\"play-btn\" alt=\"play\" type=\"image\" src=\"\/skin\/img\/play_20x20.png\">";
txt += "                    <\/div>";
txt += "                <\/div>";
txt += "            <\/form>";
txt += "        <\/div>";



        return '<div style="display:none;">' + txt + '</div>';
    })();

    return {
        skinSettingsDialog: skinSettingsDialog
    };

})();
